This run started at: 
1579048954
The zcashd version is: Zcash Daemon version v2.1.1-rc1-02706325c

In order to ensure you are adequately protecting your privacy when using Zcash,
please see <https://z.cash/support/security/>.

Copyright (C) 2009-2020 The Bitcoin Core Developers
Copyright (C) 2015-2020 The Zcash Developers

This is experimental software.

Distributed under the MIT software license, see the accompanying file COPYING
or <https://www.opensource.org/licenses/mit-license.php>.

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org/> and cryptographic software written
by Eric Young.
=== Running testscript intermittent_failures.py ===
Initializing test directory /tmp/testMQJlpc
initialize_chain: bitcoind started, calling bitcoin-cli -rpcwait getblockcount
initialize_chain: bitcoin-cli -rpcwait getblockcount completed
initialize_chain: bitcoind started, calling bitcoin-cli -rpcwait getblockcount
initialize_chain: bitcoin-cli -rpcwait getblockcount completed
initialize_chain: bitcoind started, calling bitcoin-cli -rpcwait getblockcount
initialize_chain: bitcoin-cli -rpcwait getblockcount completed
initialize_chain: bitcoind started, calling bitcoin-cli -rpcwait getblockcount
initialize_chain: bitcoin-cli -rpcwait getblockcount completed
Traceback (most recent call last):
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/intermittent_failures.py", line 58, in <module>
    WalletListNotes().main()
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/test_framework/test_framework.py", line 117, in main
    self.setup_chain()
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/test_framework/test_framework.py", line 36, in setup_chain
    initialize_chain(self.options.tmpdir)
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/test_framework/util.py", line 150, in initialize_chain
    rpcs[peer].generate(1)
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/test_framework/authproxy.py", line 145, in __call__
    response = self._request('POST', self.__url.path, postdata)
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/test_framework/authproxy.py", line 120, in _request
    return self._get_response()
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/test_framework/authproxy.py", line 160, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1148, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 404, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
!!! FAIL: intermittent_failures.py (39s) !!!



Tests completed: 1
successes 0; failures: 1

Failing tests: intermittent_failures.py
