This run started at: 
1579057836
The zcashd version is: Zcash Daemon version v2.1.1-rc1-02706325c

In order to ensure you are adequately protecting your privacy when using Zcash,
please see <https://z.cash/support/security/>.

Copyright (C) 2009-2020 The Bitcoin Core Developers
Copyright (C) 2015-2020 The Zcash Developers

This is experimental software.

Distributed under the MIT software license, see the accompanying file COPYING
or <https://www.opensource.org/licenses/mit-license.php>.

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org/> and cryptographic software written
by Eric Young.
=== Running testscript intermittent_failures.py ===
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/test_framework/test_framework.py", line 121, in main
    self.run_test()
  File "/home/pherder/zcashes/intermittenttestfailures/master/qa/rpc-tests/intermittent_failures.py", line 59, in run_test
    start = time.time()
Initializing test directory /tmp/testFp_rpn
waiting for async operation opid-7d1be6b5-bbae-4f40-aa49-4d2aa5bcd304
[{u'amount': Decimal('9.99990000'),
  u'change': False,
  u'memo': u'f600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  u'outindex': 0,
  u'txid': u'010cbb69ccb569261da8b59e96b47ca7b50e210af4a8eed830f27c41947dc517'}]
waiting for async operation opid-019948cb-43dc-43d2-9dd5-76b5248369f9
[]
Unexpected exception caught during testing: 'builtin_function_or_method' object has no attribute 'time'
Stopping nodes
Cleaning up
Failed
!!! FAIL: intermittent_failures.py (66s) !!!



Tests completed: 1
successes 0; failures: 1

Failing tests: intermittent_failures.py
